name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Conectando al VPS y actualizando
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        password: ${{ secrets.VPS_PASSWORD }}
        script: |
          set -e
          cd /var/www/Scholar-s_Sanctuary
          git config --global --add safe.directory /var/www/Scholar-s_Sanctuary
          git pull origin main
          npm install
          npm run build
          sudo systemctl restart lumina
          sudo systemctl --no-pager --full status lumina
